presets:
  staging:
    buildArgs:
      arg1: ARG1VAL
    dockerfile: .\Dockerfile
    tags:
      - "%COMMIT_HASH%"
      - latest
  production:
    buildArgs:
      arg1: ARG1VALPROD
      extra_prod: EXTRAPROD
    dockerfile: .\Dockerfile.prod
    tags:
      - "%COMMIT_HASH%"
      - latest
